config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  get 'profiles/show'
  root 'welcome#index'
  resources :users do
    resources :profiles, only: [:edit, :update, :show]
  end

  resources :coins do
    resources :comments
  end

  resources :bills do
    resources :comments
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :user
  mount_uploader :front_part_b, FrontPartBUploader
  mount_uploader :rear_part_b, RearPartBUploader
  validates_presence_of :nominal
  validates_presence_of :currency
  validates_presence_of :year
  validates_presence_of :country
  validates_presence_of :count
  has_many :comments, as: :commentable

  def nominal_currency
    "#{nominal} #{currency}"
  end
end

app/models/coin.rb
class Coin < ActiveRecord::Base
  belongs_to :user
  mount_uploader :front_part, FrontPartUploader
  mount_uploader :rear_part, RearPartUploader
  validates_presence_of :nominal
  validates_presence_of :currency
  validates_presence_of :year
  validates_presence_of :country
  validates_presence_of :count
  has_many :comments, as: :commentable

  def nominal_currency
    "#{nominal} #{currency}"
  end
end

app/models/coin_view.rb
class CoinView < ActiveRecord::Base
  belongs_to :coin
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  before_create :add_profile
  has_one :profile, dependent: :destroy
  has_many :accounts, dependent: :delete_all
  has_many :coins, dependent: :delete_all
  has_many :bills, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  private

  def add_profile
    build_profile
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :bill_resource,
                only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @bills = Bill.all
  end

  def show
    @commentable = @bill
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    redirect_to root_path unless current_user
    @bill = Bill.new
  end

  def edit
  end

  def create
    @bill = current_user.bills.create(bill_params)
    if @bill.save
      redirect_to @bill
    else
      render :new
    end
  end

  def update
    if @bill.update(bill_params)
      redirect_to @bill
    else
      render :edit
    end
  end

  def destroy
    @bill.destroy
    redirect_to bills_path
  end

  private

  def bill_params
    params.require(:bill).permit(:nominal, :currency, :year,
                                 :country,
                                 :description,
                                 :count, :front_part_b,
                                 :rear_part_b)
  end

  def bill_resource
    @bill = Bill.find(params[:id])
  end

  def require_user
    redirect_to root_path unless current_user == @bill.user
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :coin_resource,
                only: [:show, :edit, :update, :destroy]
  before_action :require_user_coins, only: [:edit, :update, :destroy]

  def index
    @coins = Coin.all
  end

  def show
    @commentable = @coin
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    redirect_to root_path unless current_user
    @coin = Coin.new
  end

  def edit
  end

  def create
    @coin = current_user.coins.create(coin_params)
    if @coin.save
      redirect_to @coin
    else
      render :new
    end
  end

  def update
    if @coin.update(coin_params)
      redirect_to @coin
    else
      render :edit
    end
  end

  def destroy
    @coin.destroy
    redirect_to coins_path
  end

  private

  def coin_params
    params.require(:coin).permit(:nominal, :currency, :year, :country,
                                 :metal, :description,
                                 :count, :front_part,
                                 :rear_part)
  end

  def coin_resource
    @coin = Coin.find(params[:id])
  end

  def require_user_coins
    redirect_to root_path unless current_user == @coin.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comments_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @commentable
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def comments_params
    params.require(:comment).permit(:commentable, :content)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :profile_resource

  def edit
  end

  def update
    @profile.update(profile_params)
    redirect_to user_profile_url
  end

  def show
    @user = User.find(params[:user_id])
  end

  private

  def profile_resource
    @profile = User.find(params[:user_id]).profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :birtday, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @account = Account.find_by(account_params)
    @account = Account.create(account_params.merge(user_params)) unless @account
    session[:user_id] = @account.user_id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

  private

  def auth_params
    request.env['omniauth.auth']
  end

  def account_params
    {
      uid: auth_params['uid'],
      provider: auth_params['provider']
    }
  end

  def user_params
    {
      user: User.find_or_create_by(email: auth_params['info']['email'])
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for singning up!'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
  def require_user_bills
    current_user == @bill.user
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
  def require_user_coins
    current_user == @coin.user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def require_user_profile
    current_user == @profile.user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Coins
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag  'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"
    link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" /
    = csrf_meta_tags
  body
    = render 'shared/header'
    = render 'shared/modal_login'
    = yield
    = render 'shared/footer'

app/views/shared/_carousel.html.slim
#carousel.carousel.slide
  ol.carousel-indicators
    li.active data-slide-to="0" data-target="#carousel"
    li data-slide-to="1" data-target="#carousel"
    li data-slide-to="2" data-target="#carousel"
  .carousel-inner
    .item.active
      = image_tag "carousel1.jpg"
    .item
      = image_tag "carousel2.jpg"
    .item
      = image_tag "carousel3.jpg"
  a.left.carousel-control data-slide="prev" href="#carousel"
    i.fa.fa-chevron-left.chevron-left_car aria-hidden="true"
  a.right.carousel-control data-slide="next" href="#carousel"
    i.fa.fa-chevron-right.chevron-right_car aria-hidden="true"

app/views/shared/_footer.html.slim
footer.section.footer
  .footer-bottom
    .container
      .col-md-12
        p
        ul.footer-share
          li
            a href="https://vk.com/crashgtafan"
              i.fa.fa-vk
          li
            a href="https://www.facebook.com/profile.php?id=100010589944972"
              i.fa.fa-facebook
          li
            a href="https://github.com/CrashGtaFan"
              i.fa.fa-github
          li
            a href="https://bitbucket.org/DanilUdalov/"
              i.fa.fa-bitbucket
        p
          | CrashGtaFan © 2016 All rights reserved. All Rights Reserved

app/views/shared/_header.html.slim
body
  header#header
    .header-content.clearfix
      = image_tag "/assets/coins_logo.png" , class: "img_logo_coins"
      nav.navigation role="navigation"
        ul.primary-nav
          li= link_to "Home", root_path
          li= link_to "Show coins", coins_path
          li= link_to "Show bills", bills_path
          - if current_user
            li= link_to "Profile", user_profile_path(current_user, current_user.profile)
            li= link_to "Log Out", logout_path
          - else
            li 
              a data-target="#myModal" data-toggle="modal"
                | Log in
      a.nav-toggle href="#"
        | Menu
        span
  #banner.banner.no-padding
    .container-fluid
      .row.no-gutter
        ul.slides
          li
            blockquote
            p.navbar-text.navbar-left.signup_name
              - if current_user
                - if current_user.profile.first_name == nil
                  p Signed in as #{current_user.email}
                - else
                  p Signed in as #{current_user.profile.full_name}

app/views/shared/_modal_login.html.slim
#myModal.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
        h4#myModalLabel.modal-title Log in
      center
        h4 Sign in with a social network
        = link_to '/auth/vkontakte' do
          span.fa-stack.fa-lg
            i.fa.fa-circle.fa-stack-2x
            i.fa.fa-vk.fa-stack-1x.fa-inverse
        = link_to '/auth/facebook' do
          span.fa-stack.fa-lg
            i.fa.fa-circle.fa-stack-2x
            i.fa.fa-facebook.fa-stack-1x.fa-inverse
      .modal-footer
        button.btn.btn-danger data-dismiss="modal" type="button"  Close