config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  get 'profiles/show'
  root 'welcome#index'
  resources :users do
    resources :profiles, only: [:edit, :update, :show]
  end

  resources :coins do
    resources :comments
  end

  resources :bills do
    resources :comments
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :user
  mount_uploader :front_part_b, FrontPartBUploader
  mount_uploader :rear_part_b, RearPartBUploader
  validates_presence_of :nominal
  validates_presence_of :currency
  validates_presence_of :year
  validates_presence_of :country
  validates_presence_of :count
  has_many :comments, as: :commentable

  def nominal_currency
    "#{nominal} #{currency}"
  end
end

app/models/coin.rb
class Coin < ActiveRecord::Base
  belongs_to :user
  mount_uploader :front_part, FrontPartUploader
  mount_uploader :rear_part, RearPartUploader
  validates_presence_of :nominal
  validates_presence_of :currency
  validates_presence_of :year
  validates_presence_of :country
  validates_presence_of :count
  has_many :comments, as: :commentable

  def nominal_currency
    "#{nominal} #{currency}"
  end
end

app/models/coin_view.rb
class CoinView < ActiveRecord::Base
  belongs_to :coin
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  before_create :add_profile
  has_one :profile, dependent: :destroy
  has_many :accounts, dependent: :delete_all
  has_many :coins, dependent: :delete_all
  has_many :bills, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  private

  def add_profile
    build_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Not authorized' unless current_user
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :bill_resource,
                only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @bills = Bill.all
  end

  def show
    @commentable = @bill
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    redirect_to root_path unless current_user
    @bill = Bill.new
  end

  def edit
  end

  def create
    @bill = current_user.bills.create(bill_params)
    if @bill.save
      redirect_to @bill
    else
      render :new
    end
  end

  def update
    if @bill.update(bill_params)
      redirect_to @bill
    else
      render :edit
    end
  end

  def destroy
    @bill.destroy
    redirect_to bills_path
  end

  private

  def bill_params
    params.require(:bill).permit(:nominal, :currency, :year,
                                 :country,
                                 :description,
                                 :count, :front_part_b,
                                 :rear_part_b)
  end

  def bill_resource
    @bill = Bill.find(params[:id])
  end

  def require_user
    redirect_to root_path unless current_user == @bill.user
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :coin_resource,
                only: [:show, :edit, :update, :destroy]
  before_action :require_user_coins, only: [:edit, :update, :destroy]

  def index
    @coins = Coin.all
  end

  def show
    @commentable = @coin
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    redirect_to root_path unless current_user
    @coin = Coin.new
  end

  def edit
  end

  def create
    @coin = current_user.coins.create(coin_params)
    if @coin.save
      redirect_to @coin
    else
      render :new
    end
  end

  def update
    if @coin.update(coin_params)
      redirect_to @coin
    else
      render :edit
    end
  end

  def destroy
    @coin.destroy
    redirect_to coins_path
  end

  private

  def coin_params
    params.require(:coin).permit(:nominal, :currency, :year, :country,
                                 :metal, :description,
                                 :count, :front_part,
                                 :rear_part)
  end

  def coin_resource
    @coin = Coin.find(params[:id])
  end

  def require_user_coins
    redirect_to root_path unless current_user == @coin.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comments_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @commentable
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def comments_params
    params.require(:comment).permit(:commentable, :content)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :profile_resource

  def edit
  end

  def update
    @profile.update(profile_params)
    redirect_to user_profile_url
  end

  def show
    @user = User.find(params[:user_id])
  end

  private

  def profile_resource
    @profile = User.find(params[:user_id]).profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :birtday, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @account = Account.find_by(account_params)
    @account = Account.create(account_params.merge(user_params)) unless @account
    session[:user_id] = @account.user_id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

  private

  def auth_params
    request.env['omniauth.auth']
  end

  def account_params
    {
      uid: auth_params['uid'],
      provider: auth_params['provider']
    }
  end

  def user_params
    {
      user: User.find_or_create_by(email: auth_params['info']['email'])
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for singning up!'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
  def require_user_bills
    current_user == @bill.user
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
  def require_user_coins
    current_user == @coin.user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def require_user_profile
    current_user == @profile.user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_form.html.slim
.container
  = form_for @bill do |f|
    - if @bill.errors.any?
      #error_explanation
        .alert.alert-danger role="alert" 
          h5
            = pluralize(@bill.errors.count, "error")
            | prohibited
            | this pet from being saved:
          ol
            - @bill.errors.full_messages.each do |msg|
              li= msg
    .row
      .col-md-4.col-xs-4
        p
          = f.label :nominal
          br/
          = f.text_field :nominal, class: 'form-control'
      .col-md-4.col-xs-4
        p
          = f.label :currency
          br/
          = f.text_field :currency, class: 'form-control'
      .col-md-4.col-xs-4
        p
          = f.label :year
          br/
          = f.text_field :year, class: 'form-control'
    .row
      .col-md-4.col-xs-4
        p
          = f.label :country
          br/
          = f.text_field :country, class: 'form-control'
      .col-md-4.col-xs-12
        p
          = f.label :count
          br/
          = f.text_field :count, type: 'number', min: "0", class: 'form-control'
    .row
      .col-md-12.col-xs-12
        p
          = f.label :description
          br/
          = f.text_area :description, class: 'form-control'
    .row
      .col-md-4.col-xs-6
        p
          = f.label :front_part_b
          br/
          = f.file_field :front_part_b, class: 'file_front_part'
        .upload-preview_front_part
          img.upload_front_part/
      .col-md-4.col-xs-6
        p
          = f.label :rear_part_b
          br/
          = f.file_field :rear_part_b, class: 'file_rear_part'
        .upload-preview_rear_part
          img.upload_rear_part/
      .col-md-4.col-xs-12
        = link_to 'Back', bills_path, class: 'btn btn-primary'
        = f.submit 'Add', class: 'btn btn-success'

app/views/bills/edit.html.slim
center
  h3 Edit bills
= render 'form'

app/views/bills/index.html.slim
section#teams.section.teams
  center
    - if current_user
      = link_to 'New bills', new_bill_path, class: 'btn btn-success'
  p
  - @bills.each do |bill|
    .col-sm-6.col-md-4
      .thumbnail
        = image_tag bill.front_part_b.url(:thumb), class: "img_bills_index"
        .caption
          h4= link_to bill.nominal_currency, bill

app/views/bills/new.html.slim
center
  h3 New bills
= render 'form'

app/views/bills/show.html.slim
.container
  .well
    .row
      .col-md-6.col-xs-12
        = image_tag @bill.front_part_b.url(:large), class: "img_bills_show"
        p Front part
      .col-md-6.col-xs-12
        = image_tag @bill.rear_part_b.url(:large), class: "img_bills_show"
        p Rear part
    .row
      .col-md-9.col-xs-12
        table.table.table-bordered
          thead
            tr
              th Name
              th Year
              th Country
              th Coint
          tbody
            td
              = @bill.nominal_currency
            td
              = @bill.year
            td 
              = @bill.country
            td
              = @bill.count
        b Description
        p
          = @bill.description.html_safe
      .col-md-3.col-xs-12
        .list-group
          = link_to 'Back', bills_path, class: "list-group-item"
          - if require_user_bills
            = link_to 'Edit', edit_bill_path(@bill), class: "list-group-item"
            = link_to 'Destroy', bill_path(@bill), method: :delete, data: { confirm: 'Are  you sure?' }, class: "list-group-item"
    .row.comment
      = render "comments/comments"
      = render "comments/form"

app/views/coins/_form.html.slim
.container
  = form_for @coin do |f|
    - if @coin.errors.any?
      #error_explanation
        .alert.alert-danger role="alert" 
          h5
            = pluralize(@coin.errors.count, "error")
            | prohibited
            | this pet from being saved:
          ol
            - @coin.errors.full_messages.each do |msg|
              li= msg
    .row
      .col-md-4.col-xs-4
        p
          = f.label :nominal
          br/
          = f.text_field :nominal, class: 'form-control'
      .col-md-4.col-xs-4
        p
          = f.label :currency
          br/
          = f.text_field :currency, class: 'form-control'
      .col-md-4.col-xs-4
        p
          = f.label :year
          br/
          = f.text_field :year, class: 'form-control'
    .row
      .col-md-4.col-xs-4
        p
          = f.label :country
          br/
          = f.text_field :country, class: 'form-control'
      .col-md-4.col-xs-4
        p
          = f.label :metal
          br/
          = f.text_field :metal, class: 'form-control'
      .col-md-4.col-xs-12
        p
          = f.label :count
          br/
          = f.text_field :count, type: 'number', min: "0", class: 'form-control'
    .row
      .col-md-12.col-xs-12
        p
          = f.label :description
          br/
          = f.text_area :description, class: 'form-control'
    .row
      .col-md-4.col-xs-6
        p
          = f.label :front_part
          br/
          = f.file_field :front_part, class: 'file_front_part'
        .upload-preview_front_part
          img.upload_front_part/
      .col-md-4.col-xs-6
        p
          = f.label :rear_part
          br/
          = f.file_field :rear_part, class: 'file_rear_part'
        .upload-preview_rear_part
          img.upload_rear_part/
      .col-md-4.col-xs-12
        = link_to 'Back', coins_path, class: 'btn btn-primary'
        = f.submit 'Add', class: 'btn btn-success'

app/views/coins/edit.html.slim
center
  h3 Edit coins
= render 'form'

app/views/coins/index.html.slim
section#teams.section.teams
  center
    - if current_user
      = link_to 'New coins', new_coin_path, class: 'btn btn-success'
  p
  - @coins.each do |coin|
    .col-sm-6.col-md-4
      .thumbnail
        = image_tag coin.front_part.url(:thumb), class: "img_coins_index img-rounded"
        .caption
          h4= link_to coin.nominal_currency, coin

app/views/coins/new.html.slim
center
  h3 New coins
= render 'form'

app/views/coins/show.html.slim
.container
  .well
    .row
      .col-md-6.col-xs-12
        = image_tag @coin.front_part.url(:large), class: "img_coins_show img-circle"
        p Front part
      .col-md-6.col-xs-12
        = image_tag @coin.rear_part.url(:large), class: "img_coins_show img-circle"
        p Rear part
    .row
      .col-md-9.col-xs-12
        table.table.table-bordered
          thead
            tr
              th Name
              th Year
              th Country
              th Metal
              th Coint
          tbody
            td
              = @coin.nominal_currency
            td
              = @coin.year
            td 
              = @coin.country
            td
              = @coin.metal
            td
              = @coin.count
        b Description
        p
          = @coin.description.html_safe
      .col-md-3.col-xs-12
        .list-group
          = link_to 'Back', coins_path, class: "list-group-item"
          - if require_user_coins
            = link_to 'Edit', edit_coin_path(@coin), class: "list-group-item"
            = link_to 'Destroy', coin_path(@coin), method: :delete, data: { confirm: 'Are  you sure?' }, class: "list-group-item"
    .row.comment
      = render "comments/comments"
      = render "comments/form"

app/views/comments/_comments.html.slim
.container
  - @comments.each do |comment|
    .row
      .comment
        .col-md-1.col-xs-2
          = image_tag comment.user.profile.avatar.url(:small), class: "img-circle user_image_small" unless comment.user.blank?
        .col-md-4.col-xs-9
          b
            - if comment.user.profile.first_name == nil
              = comment.user.email
            - else
              = comment.user.profile.full_name
          = simple_format comment.content
          p.comment_time
          = time_ago_in_words(comment.created_at)
          |  Ago
          p
        .col-md-1.col-xs-1
        - if current_user
          - if current_user.id == comment.user_id
            = link_to 'X', [comment.commentable, comment], method: :delete, remote: true, data: {confirm: 'Are you sure?'}
          - elsif current_user.id == @commentable.user_id
            = link_to 'X', [comment.commentable, comment], method: :delete, remote: true, data: {confirm: 'Are you sure?'}
    br

app/views/comments/_form.html.slim
.container
  = form_for [@commentable, @comment], remote: true do |f|
    - if @comment.errors.any?
      #error_explanation
        .alert.alert-danger role="alert" 
          h5
            = pluralize(@comment.errors.count, "error")
            | prohibited
            | this pet from being saved:
          ol
            - @comment.errors.full_messages.each do |msg|
              li= msg
    .row
      .col-md-8.col-xs-12
        p
          = f.label :content
          br/
          = f.text_area :content, class: 'form-control'
        p
          = f.submit class: 'btn btn-success'

app/views/comments/create.js.slim
$('#comments').html("#{j (render @comment)}");

app/views/comments/destroy.js.slim
$('#comment_#{@comment.id}').remove();

app/views/comments/index.html.slim
h1 Comments
= render 'comments'
= link_to "New comment", [:new, @commentable, :comment]

app/views/comments/new.html.slim
h1 New comment
= render "form"

app/views/profiles/edit.html.slim
.container
  = form_for [current_user, @profile] do |f|
    .row
      .col-md-6.col-xs-12.col-md-offset-3
        p
          = f.label :first_name
          br/
          = f.text_field :first_name, class: 'form-control'
        p
          = f.label :last_name
          br/
          = f.text_field :last_name, class: 'form-control'
        p
          = f.label :birtday
          br/
          = f.text_field :birtday, type: 'date', class: 'form-control'
        p
          = f.label :avatar
          br/
          = f.file_field :avatar, class: 'file_avatar'
        p
          = f.submit 'Update', class: 'btn btn-success'

app/views/profiles/show.html.slim
.container
  .well
    .media
      .media-left
        p
          = image_tag @profile.avatar.url(:large), class: "img_avatar_show img-rounded"
      .media-body
        h2 Profile info
        table.table
          tr
            th Email
            td
              = @profile.user.email
          tr
            th Full name
            td
              = @profile.full_name
          tr
            th Birtday
            td
              = @profile.birtday
        .btn-group
          = link_to 'Back', coins_path, class: "btn btn-primary back_button"
          - if require_user_profile
            = link_to 'Edit', edit_user_profile_url, class: "btn btn-warning back_edit"

app/views/welcome/index.html.slim
= render 'shared/carousel'
section#teams.section.teams
  .container
    .row
      .col-md-5.col-sm-4
        .bio
          = image_tag "/assets/coins.jpg" , class: "img_coins"
      .col-md-7.col-sm-8
        .bio
          .bio-content
            h4 Welcome
            h5 UX/UI Designer, Front-end Developer
            p Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas sed diam eget risus varius blandit sit amet non magna. Nullam quis risus eget urna mollis ornare tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas sed diam eget risus varius blandit sit amet non magna. Nullam quis risus eget urna mollis ornare vel eu leo.tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas sed diam eget risus varius blandit sit amet non magna. Nullam quis risus eget urna mollis ornare vel eu leo.vel eu leo.